FROM registry.access.redhat.com/ubi9/go-toolset:1.21.13-2.1729776560 as validator
WORKDIR /build
COPY  --chown=1001:0 . .
RUN go install github.com/golang/mock/mockgen && \
    go install github.com/Khan/genqlient
RUN make generate gotest
