// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package producer

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/app-sre/go-qontract-reconcile/pkg/gql"
)

// GetGitlabSyncAppsApps_v1App_v1 includes the requested fields of the GraphQL type App_v1.
type GetGitlabSyncAppsApps_v1App_v1 struct {
	CodeComponents []GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1 `json:"codeComponents"`
}

// GetCodeComponents returns GetGitlabSyncAppsApps_v1App_v1.CodeComponents, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1) GetCodeComponents() []GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1 {
	return v.CodeComponents
}

// GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1 includes the requested fields of the GraphQL type AppCodeComponents_v1.
type GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1 struct {
	GitlabSync GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1 `json:"gitlabSync"`
}

// GetGitlabSync returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1.GitlabSync, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1) GetGitlabSync() GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1 {
	return v.GitlabSync
}

// GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1 includes the requested fields of the GraphQL type CodeComponentGitlabSync_v1.
type GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1 struct {
	SourceProject      GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1      `json:"sourceProject"`
	DestinationProject GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1 `json:"destinationProject"`
}

// GetSourceProject returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1.SourceProject, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1) GetSourceProject() GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1 {
	return v.SourceProject
}

// GetDestinationProject returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1.DestinationProject, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1) GetDestinationProject() GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1 {
	return v.DestinationProject
}

// GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1 includes the requested fields of the GraphQL type CodeComponentGitlabSyncProject_v1.
type GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1 struct {
	Name   string `json:"name"`
	Group  string `json:"group"`
	Branch string `json:"branch"`
}

// GetName returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1.Name, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1) GetName() string {
	return v.Name
}

// GetGroup returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1.Group, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1) GetGroup() string {
	return v.Group
}

// GetBranch returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1.Branch, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1DestinationProjectCodeComponentGitlabSyncProject_v1) GetBranch() string {
	return v.Branch
}

// GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1 includes the requested fields of the GraphQL type CodeComponentGitlabSyncProject_v1.
type GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1 struct {
	Name   string `json:"name"`
	Group  string `json:"group"`
	Branch string `json:"branch"`
}

// GetName returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1.Name, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1) GetName() string {
	return v.Name
}

// GetGroup returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1.Group, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1) GetGroup() string {
	return v.Group
}

// GetBranch returns GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1.Branch, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsApps_v1App_v1CodeComponentsAppCodeComponents_v1GitlabSyncCodeComponentGitlabSync_v1SourceProjectCodeComponentGitlabSyncProject_v1) GetBranch() string {
	return v.Branch
}

// GetGitlabSyncAppsResponse is returned by GetGitlabSyncApps on success.
type GetGitlabSyncAppsResponse struct {
	Apps_v1 []GetGitlabSyncAppsApps_v1App_v1 `json:"apps_v1"`
}

// GetApps_v1 returns GetGitlabSyncAppsResponse.Apps_v1, and is useful for accessing the field via an interface.
func (v *GetGitlabSyncAppsResponse) GetApps_v1() []GetGitlabSyncAppsApps_v1App_v1 { return v.Apps_v1 }

// GetSaasResourceTemplateRefsResponse is returned by GetSaasResourceTemplateRefs on success.
type GetSaasResourceTemplateRefsResponse struct {
	Saas_files []GetSaasResourceTemplateRefsSaas_filesSaasFile_v2 `json:"saas_files"`
}

// GetSaas_files returns GetSaasResourceTemplateRefsResponse.Saas_files, and is useful for accessing the field via an interface.
func (v *GetSaasResourceTemplateRefsResponse) GetSaas_files() []GetSaasResourceTemplateRefsSaas_filesSaasFile_v2 {
	return v.Saas_files
}

// GetSaasResourceTemplateRefsSaas_filesSaasFile_v2 includes the requested fields of the GraphQL type SaasFile_v2.
type GetSaasResourceTemplateRefsSaas_filesSaasFile_v2 struct {
	Name              string                                                                                     `json:"name"`
	ResourceTemplates []GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2 `json:"resourceTemplates"`
}

// GetName returns GetSaasResourceTemplateRefsSaas_filesSaasFile_v2.Name, and is useful for accessing the field via an interface.
func (v *GetSaasResourceTemplateRefsSaas_filesSaasFile_v2) GetName() string { return v.Name }

// GetResourceTemplates returns GetSaasResourceTemplateRefsSaas_filesSaasFile_v2.ResourceTemplates, and is useful for accessing the field via an interface.
func (v *GetSaasResourceTemplateRefsSaas_filesSaasFile_v2) GetResourceTemplates() []GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2 {
	return v.ResourceTemplates
}

// GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2 includes the requested fields of the GraphQL type SaasResourceTemplate_v2.
type GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2 struct {
	Targets []GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2TargetsSaasResourceTemplateTarget_v2 `json:"targets"`
}

// GetTargets returns GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2.Targets, and is useful for accessing the field via an interface.
func (v *GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2) GetTargets() []GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2TargetsSaasResourceTemplateTarget_v2 {
	return v.Targets
}

// GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2TargetsSaasResourceTemplateTarget_v2 includes the requested fields of the GraphQL type SaasResourceTemplateTarget_v2.
type GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2TargetsSaasResourceTemplateTarget_v2 struct {
	Ref string `json:"ref"`
}

// GetRef returns GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2TargetsSaasResourceTemplateTarget_v2.Ref, and is useful for accessing the field via an interface.
func (v *GetSaasResourceTemplateRefsSaas_filesSaasFile_v2ResourceTemplatesSaasResourceTemplate_v2TargetsSaasResourceTemplateTarget_v2) GetRef() string {
	return v.Ref
}

func GetGitlabSyncApps(
	ctx context.Context,
) (*GetGitlabSyncAppsResponse, error) {
	req := &graphql.Request{
		OpName: "GetGitlabSyncApps",
		Query: `
query GetGitlabSyncApps {
	apps_v1 {
		codeComponents {
			gitlabSync {
				... on CodeComponentGitlabSync_v1 {
					sourceProject {
						... on CodeComponentGitlabSyncProject_v1 {
							name
							group
							branch
						}
					}
					destinationProject {
						... on CodeComponentGitlabSyncProject_v1 {
							name
							group
							branch
						}
					}
				}
			}
		}
	}
}
`,
	}
	var err error
	var client graphql.Client

	client, err = gql.NewQontractClient(ctx)
	if err != nil {
		return nil, err
	}

	var data GetGitlabSyncAppsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func GetSaasResourceTemplateRefs(
	ctx context.Context,
) (*GetSaasResourceTemplateRefsResponse, error) {
	req := &graphql.Request{
		OpName: "GetSaasResourceTemplateRefs",
		Query: `
query GetSaasResourceTemplateRefs {
	saas_files: saas_files_v2 {
		name
		resourceTemplates {
			targets {
				ref
			}
		}
	}
}
`,
	}
	var err error
	var client graphql.Client

	client, err = gql.NewQontractClient(ctx)
	if err != nil {
		return nil, err
	}

	var data GetSaasResourceTemplateRefsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
